import React, { useState, useEffect, useRef } from 'react';

// Code Snippets for the left column
const CODE_SNIPPETS = {
  1: `-- Step 1: Clean and sequence the raw event data
SELECT 
    match_id,
    team_id,
    timestamp_minute,
    timestamp_second,
    event_type,
    ISNULL(expected_goals, 0) AS xG,
    ISNULL(expected_threat, 0) AS xT
FROM Fact_Event
WHERE event_type IN ('Pass', 'Shot', 'Dribble') 
  AND is_successful = 1;`,

  2: `# Step 2: Offline Pre-Match Logistic Regression
from sklearn.linear_model import LogisticRegression

def train_pre_match_model(features_df):
    X = features_df[['home_xG_diff', 'away_xG_diff', 'days_rest']]
    y = features_df['match_result']
    
    model = LogisticRegression(multi_class='multinomial')
    model.fit(X_train, y_train)
    
    return model.predict_proba(X_test)`,

  3: `-- Step 3: The Alpha Query - Rolling Momentum
SELECT 
    team_id,
    timestamp_minute,
    SUM(xT) OVER (
        PARTITION BY match_id, team_id 
        ORDER BY match_event_sequence 
        ROWS BETWEEN 14 PRECEDING AND CURRENT ROW
    ) AS rolling_15_event_xT,
    
    timestamp_minute - LAG(timestamp_minute, 1) OVER (
        PARTITION BY match_id, team_id, CASE WHEN event_type = 'Shot' THEN 1 ELSE 0 END
        ORDER BY match_event_sequence
    ) AS minutes_since_last_shot
FROM EventStream;`,

  4: `{
  "timestamp": "72:14",
  "trigger": "ALPHA_DETECTED",
  "metrics": {
    "rolling_xT_spike": "+2.4",
    "market_implied_prob": "22.5%",
    "model_true_prob": "35.0%"
  },
  "execution": {
    "action": "PLACE_BET",
    "expected_value": "+12.5%",
    "stake": "2 Units"
  },
  "status": "LOCKED"
}`
};

const Step = ({ id, activeStep, title, children }) => {
  const isActive = activeStep === id;
  return (
    <div 
      data-step={id} 
      className={`step-container min-h-[85vh] transition-opacity duration-700 flex flex-col justify-center ${isActive ? 'opacity-100' : 'opacity-20'}`}
    >
      <h2 className="text-3xl font-bold text-emerald-400 mb-4">{title}</h2>
      <div className="text-lg text-slate-300 mb-8 leading-relaxed">
        {children}
      </div>
      <div className="bg-slate-950 p-6 rounded-lg font-mono text-sm border border-slate-800 shadow-2xl">
        <div className="flex gap-2 mb-4">
          <div className="w-3 h-3 rounded-full bg-red-500"></div>
          <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
          <div className="w-3 h-3 rounded-full bg-green-500"></div>
        </div>
        <pre className="text-emerald-300 whitespace-pre-wrap overflow-x-auto">
          {CODE_SNIPPETS[id]}
        </pre>
      </div>
    </div>
  );
};

export default function App() {
  const [activeStep, setActiveStep] = useState(1);
  const [matchData, setMatchData] = useState([]);
  const canvasRef = useRef(null);

  // Fetch the real StatsBomb data generated by your Python script
  useEffect(() => {
    fetch('/match_data.json')
      .then((res) => res.json())
      .then((data) => setMatchData(data));
  }, []);
  
  // Intersection Observer for scroll tracking
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveStep(Number(entry.target.getAttribute('data-step')));
          }
        });
      },
      { rootMargin: '-40% 0px -40% 0px' }
    );

    document.querySelectorAll('.step-container').forEach((step) => {
      observer.observe(step);
    });

    return () => observer.disconnect();
  }, []);

  // Canvas Animation Logic
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas || matchData.length === 0) return;
    const ctx = canvas.getContext('2d');
    let animationFrameId;
    let time = 0; // Starts at minute 0

    const render = () => {
      // Step 4 Freeze State
      if (activeStep === 4) {
        ctx.fillStyle = 'rgba(15, 23, 42, 0.1)'; 
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        ctx.fillStyle = 'rgba(16, 185, 129, 0.2)'; // Emerald wash
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        
        ctx.font = 'bold 48px monospace';
        ctx.fillStyle = '#34d399';
        ctx.textAlign = 'center';
        ctx.fillText('🚨 ALPHA DETECTED 🚨', canvas.width / 2, canvas.height / 2);
        ctx.font = '24px monospace';
        ctx.fillText('MARKET EV: +12.5% | TRADE EXECUTED', canvas.width / 2, (canvas.height / 2) + 40);
        return; // Halt animation loop
      }

      // Normal Animation State
      time += 0.05; // Playback speed
      const matchMinute = time % 100; // Loop every 100 match minutes
      
      canvas.width = canvas.parentElement.clientWidth;
      canvas.height = canvas.parentElement.clientHeight;

      ctx.fillStyle = '#0f172a'; // slate-900 pitch
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      // Draw pitch lines
      ctx.strokeStyle = '#1e293b';
      ctx.lineWidth = 2;
      ctx.strokeRect(40, 40, canvas.width - 80, canvas.height - 80);
      ctx.beginPath();
      ctx.moveTo(canvas.width / 2, 40);
      ctx.lineTo(canvas.width / 2, canvas.height - 40);
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(canvas.width / 2, canvas.height / 2, 50, 0, Math.PI * 2);
      ctx.stroke();

      // Map StatsBomb 120x80 coordinates to current Canvas size
      const scaleX = canvas.width / 120;
      const scaleY = canvas.height / 80;

      // Filter events up to current match minute and show the last 15
      const visibleEvents = matchData
        .filter((d) => d.time <= matchMinute)
        .slice(-15);

      visibleEvents.forEach((event, i) => {
        const cx = event.x * scaleX;
        const cy = event.y * scaleY;
        
        ctx.beginPath();
        ctx.arc(cx, cy, event.type === 'Shot' ? 8 : 4, 0, Math.PI * 2);
        ctx.fillStyle = event.type === 'Shot' ? '#ef4444' : (activeStep === 3 ? '#34d399' : '#3b82f6');
        ctx.fill();

        // Draw passing connection lines
        if (i > 0) {
            const prevEvent = visibleEvents[i - 1];
            const px = prevEvent.x * scaleX;
            const py = prevEvent.y * scaleY;
            
            ctx.beginPath();
            ctx.moveTo(cx, cy);
            ctx.lineTo(px, py);
            ctx.strokeStyle = activeStep === 3 ? 'rgba(52, 211, 153, 0.4)' : 'rgba(59, 130, 246, 0.4)';
            ctx.stroke();
        }
      });

      // Live metrics overlay for Step 3
      if (activeStep === 3 && visibleEvents.length > 0) {
        const latestEvent = visibleEvents[visibleEvents.length - 1];
        ctx.font = '20px monospace';
        ctx.textAlign = 'left';
        
        ctx.fillStyle = '#94a3b8';
        ctx.fillText(`Match Minute: ${Math.floor(matchMinute)}'`, 60, 50);
        
        ctx.fillStyle = '#34d399';
        ctx.fillText(`Rolling xT: ${latestEvent.rolling_xT.toFixed(2)}`, 60, 80);
        
        ctx.fillStyle = '#ef4444';
        ctx.fillText(`Market EV: -0.2%`, 60, 110);
      }

      animationFrameId = requestAnimationFrame(render);
    };

    render();

    return () => cancelAnimationFrame(animationFrameId);
  }, [activeStep, matchData]);

  return (
    <div className="h-screen w-full bg-slate-900 text-white overflow-hidden grid grid-cols-2 font-sans">
      
      {/* Left Column - Scrollable */}
      <div className="h-full overflow-y-auto pb-[40vh] pt-[20vh] px-12 hide-scrollbar">
        <div className="max-w-xl mx-auto">
          <div className="mb-[20vh]">
            <h1 className="text-5xl font-extrabold mb-4 tracking-tight">Finding the Alpha</h1>
            <p className="text-xl text-slate-400">Quantitative sports trading & real-time event prediction.</p>
          </div>

          <Step id={1} activeStep={activeStep} title="1. Ingest & Normalize">
            Raw spatial event data (StatsBomb) is messy. Before modeling, we normalize X/Y pitch coordinates and handle null states to ensure pristine tick data for the algorithms.
          </Step>

          <Step id={2} activeStep={activeStep} title="2. The Offline Model">
            Before kickoff, a multi-class Logistic Regression model trained on historical data sets the baseline. We strictly enforce temporal splits to prevent data leakage.
          </Step>

          <Step id={3} activeStep={activeStep} title="3. The Live Engine">
            As the match progresses, advanced SQL Server Window Functions calculate rolling attacking momentum (Expected Threat - xT). We compare our live true probability against the bookmaker's implied probability.
          </Step>

          <Step id={4} activeStep={activeStep} title="4. The Execution">
            When rolling momentum spikes dramatically but the market odds lag behind, the system detects a mathematical advantage (+EV). We freeze the analysis and execute the trade.
          </Step>
        </div>
      </div>

      {/* Right Column - Fixed Canvas */}
      <div className="h-full w-full bg-slate-950 relative border-l border-slate-800">
        <canvas 
          ref={canvasRef} 
          className="absolute inset-0 w-full h-full"
        />
        <div className="absolute bottom-6 right-6 text-slate-500 font-mono text-xs">
          LIVE TICK DATA STREAM
        </div>
      </div>
      
    </div>
  );
}